### ISSUE TITLE
[Time sensitive] Calling a global parameter from the URL

### ISSUE THREAD

**Issue by danielmlow** [danielmlow/WellBeingStudy_test#1]
@satra @sanu

I want to show participants a certain item depending on the day of the study from 1 to 28. The easiest way I can think of is setting a parameter in the URL to the day they're in which can be calculated locally. 

I’m trying to call a global parameter from the URL called `myParameter` (at the end of the URL): 

``` 
https://danielmlow.github.io/WellBeingStudy_test/#/?auth_token=WellBeingStudy_test-6c3c33dc015e4b2d99626483c92f8a5f&expiry_time=2021-10-31T18:37:23.209676+00:00&uid=en_9999&lang=en&myParameter=2
```

so I want to show certain items depending on the value, so I did this:

```
https://github.com/danielmlow/WellBeingStudy_test/blob/1a4b1615e978fc23dd291986223bd8360d2094d6/activities/audio_check/audio_check_schema#L21
```

But when I run that URL at the top it just ignores the two items does the audio_check and goes onto the next activity

* ![image](https://user-images.githubusercontent.com/14787791/139491814-4eb098db-2393-4608-99d0-1028ba41ce64.png)

if I run the following, it shows both, not respecting the isVis:

```
https://www.repronim.org/reproschema-ui/#/?url=https://raw.githubusercontent.com/danielmlow/WellBeingStudy_test/master/protocol/WellBeing_schema
```

* ![image](https://user-images.githubusercontent.com/14787791/139491851-5cd38913-1c27-4870-99b8-65720e859ed4.png)

**Comment by djarecka** [comment]
I can see an error that `myParameter` is not defined. Where do you actually set or calculate it?

**Comment by djarecka** [comment]
oh sorry, you're trying to provide it through URL...

**Comment by danielmlow** [comment]
Yeah. I need to show an item based on `myParameter`, which in our study is which day of the study they're on out of 28 days. Alternatively, I could have the user insert it because I state it in their daily email, but they may make a mistake. Or I set up 28 different repos and direct people to each one depending on the day :) 

So it seems calling it from the URL is the easiest, and will be helpful for other projects in the future. 

@sanuann, any intuition on a solution for this for @djarecka would be super helpful!

**Comment by satra** [comment]
the framework already absorbs url parameters like expiry time, uid, and auth token. so there is already a mechanism in place. the main thing is to accept other variables from the url and making it accessible in a variable store for use in javascript comparisons.

**Comment by djarecka** [comment]
Yesterday was having issue with reading the url parameters in `App.vue` (even the one that exist, e.g. `lang`), but will try again

**Comment by djarecka** [comment]
I was having problem with it, but decided to use an approach where you simply set a number to `isVis` and use `param_vis` in the url. See changes in [reproschema-ui](https://github.com/ReproNim/reproschema-ui/pull/282) and [an example from demo](https://github.com/ReproNim/demo-protocol/pull/19)

Let me know if this would work for you

**Comment by djarecka** [comment]
@danielmlow - please ignore my PRs and comments. Looks like you can change the parameter to "week" (i.e. in the url `?week=2`) and this should work

**Comment by danielmlow** [comment]
Thank you! 

Only week or any available string?

**Comment by satra** [comment]
You can use any string, but just do a string comparison in `isVis` rather
than a numeric comparison

**Comment by danielmlow** [comment]
Works! 

To recap: add any string as a new parameter, in this case `myParameter=2`: 
https://danielmlow.github.io/WellBeingStudy_test/#/?auth_token=test-f167b386f9e54be9aaca890be3fcca69&expiry_time=2021-11-07T23:48:39.816473+00:00&uid=en_9999&lang=en&myParameter=2

and then use isVis string comparison:

"isVis": "myParameter === '2'"


Thanks @djarecka and @satra!
